### ISSUE TITLE
camerastream widget doesn't work on appdaemon4?

### ISSUE THREAD

**Issue by fribse** [tjntomas/HADashboard-widgets#13]
Hi @tjntomas 
Thankyou for this great widget.
I've had to move to appdaemon4 to get controllerx running.
But that made the widget fail with this message:

HA: 0.105.3
AppDaemon4 (0.1.2)
WallPanel (by thanksmister)

```
    frontdoor: Error in widget definition '%s':
    frontdoor: parser says
    frontdoor: in "", line 2, column 10: entity: {{entity}} ^
    frontdoor: found unhashable key while constructing a mapping

```

**Comment by tjntomas** [comment]
Yes, a change in the yaml compnent requires a change in the .yaml file.

Edit your camerastream.yaml file to as per below:
````yaml

widget_type: basecamerastream
entity: "{{entity}}"
fields:
  title: ""
  base_url: ""
  image_style: ""
  
  img_internal_src: ""
  img_internal_style: ""
icons: []
static_css:
  title_style: $style_title
  widget_style: $background_style
css: []
static_icons: []
````
and the widget should work with AD4.
