### ISSUE TITLE
Local time

### ISSUE THREAD

**Issue by tollerm** [tjntomas/HADashboard-widgets#9]
it seems that the hagraph widget uses UTC time when plotting histories from the Home Assistant. Is it possible to plot sensors data using local time?

**Comment by tjntomas** [comment]
add:
````yaml
time_zone: Europe/Stockholm  # Use your time zone here
````
to the widget.

**Comment by tollerm** [comment]
Thanks! It works when I put this line into the 'variables.yaml' file. While it doea not matter, may be, it would be better to assign the value to this variable in the 'main.dash' file? And to do the same for variables hagraph.path and hagraph.token. It seems for me a little bit illogical  to assign values to these variables in the css folder. 
Thanks again for your prompt help.

**Comment by tjntomas** [comment]
Yes, it would be better to have it in the main options in the dash file, but these parameters are not exposed by appdaemon to the widget so there is no way of accessing them from javascript.

**Comment by tjntomas** [comment]
I will however add an option to add token etct to the widget parameters. The reason I put them in the css is so I don´t have to add them to each and every widget since I have a lot.

**Comment by tuananh1094** [comment]
Hi tjntomas, I try add my "time_zone: Asia/Ho_Chi_Minh" to widgets definition, but time in my graph is not true. Can you help me fix it?

**Comment by tjntomas** [comment]
time_zone: Asia/Ho_Chi_Minh  works fine when I try it. Hve you trie clearing the browseer cache or recompiling the widget?

**Comment by tuananh1094** [comment]
Thank you for your prompt response, I tried clearing browser cache and recompiling but it stills not work for me. I try put "time_zone" in *variables.yaml* or in my dashboard, but nothing changed. You can see my config below:
* in variables.yaml
```yaml
graph_style: "border-radius: 0px; background-color: rgba(30,30,30,0.45);"  # Change to whichever css you like.
graph_legend_text_color: "#888888"
graph_grid_color: "#888"
graph_title_color: "#cccccc"
graph_x_axis_text_color: "#cccccc"
graph_y_axis_legend_color: "#cccccc"
graph_y_axis_text_color: "#cccccc"
graph_widget_style: "border-bottom-left-radius: 10px;border-bottom-right-radius: 10px;border-top-left-radius: 10px;border-top-right-radius: 10px;"
graph_trace_colors: "1"  # Set the opacity for the trace colors.
graph_fill_colors: "1"   # Set the opacity for the fill colors.
graph_bar_colors: "1"    # Set the opacity for the bar colors.
graph_bar_multi: "1"     # Leave this as is
graph_degrees_celsius_text: "Degrees Celsius"  # Adjust to your own language
graph_degrees_fahrenheit_text: "Degrees Fahrenheit"  # Adjust to your own language
graph_percent_text: "Percent"  # Adjust to your own language
hagraph_path: https://myhome.duckdns.org:8123  # Adjust the port if needed.
hagraph_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmOTU4ZjlkOTZkODc0Mzc0OTI0ZWEzYTRhYTE1ZDJkOSIsImlhdCI6MTU1ODY5MzQyMSwiZXhwIjoxODc0MDUzNDIxfQ.QKNcm2Ggtnna6B1VHDFVpyy2qU3PW9c6oVmwPWYeVHM
time_zone: Asia/Ho_Chi_Minh
```
* in mydashboard.dash
```dash
temperature:
  widget_type: hagraph
  entities:
    - sensor.temperature
  units: ""
  titles:
    - "Temperature(°C)"
  time: 24h
  time_zone: Asia/Ho_Chi_Minh
  title: "Temperature"
  value_in_legend: 1
  fill: "tozeroy"
  colorIndex: 0
  log: 1
```

**Comment by tjntomas** [comment]
Just noticed that you are using the hagraph widget. I only implemented the time_zone for the graph widget. I'll upload a new basehagraph.js in a bit.

**Comment by tjntomas** [comment]
Ok, so the repo is updated. you need to replace your existing basehagraph.js file with the new one from [here](https://github.com/tjntomas/HADashboard-widgets/tree/master/custom_widgets/basehagraph). I have added some debug so the javascript console should log the current time zone settings etc.

**Comment by tuananh1094** [comment]
I tried with new *basehagraph.js* file and *locale: vi* in my widget def  but i received an error below:
![Capture](https://user-images.githubusercontent.com/33253219/58608283-0d9fe500-82cd-11e9-84af-9558482f5853.PNG)
I had a config *cors_allowed_origins* in my *configuration.yaml*
```yaml
http:
  base_url: https://myhome.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  api_password: "my pass"
  cors_allowed_origins:
    - https://192.168.xx.xx:8123
    - https://myhome.duckdns.org:8123 
    - https://myhome.duckdns.org:5050
```
